//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFVideos.WebUI.ServicoDeGestaoDeCredito {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proposta", Namespace="http://schemas.datacontract.org/2004/07/WCFVideos.Contratos")]
    [System.SerializableAttribute()]
    public partial class Proposta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFVideos.WebUI.ServicoDeGestaoDeCredito.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFVideos.WebUI.ServicoDeGestaoDeCredito.Emprestimo EmprestimoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFVideos.WebUI.ServicoDeGestaoDeCredito.Status StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFVideos.WebUI.ServicoDeGestaoDeCredito.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFVideos.WebUI.ServicoDeGestaoDeCredito.Emprestimo Emprestimo {
            get {
                return this.EmprestimoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmprestimoField, value) != true)) {
                    this.EmprestimoField = value;
                    this.RaisePropertyChanged("Emprestimo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFVideos.WebUI.ServicoDeGestaoDeCredito.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/WCFVideos.Contratos")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Idade {
            get {
                return this.IdadeField;
            }
            set {
                if ((this.IdadeField.Equals(value) != true)) {
                    this.IdadeField = value;
                    this.RaisePropertyChanged("Idade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Salario {
            get {
                return this.SalarioField;
            }
            set {
                if ((this.SalarioField.Equals(value) != true)) {
                    this.SalarioField = value;
                    this.RaisePropertyChanged("Salario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Emprestimo", Namespace="http://schemas.datacontract.org/2004/07/WCFVideos.Contratos")]
    [System.SerializableAttribute()]
    public partial class Emprestimo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantidadeDeParcelasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TaxaDeJurosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuantidadeDeParcelas {
            get {
                return this.QuantidadeDeParcelasField;
            }
            set {
                if ((this.QuantidadeDeParcelasField.Equals(value) != true)) {
                    this.QuantidadeDeParcelasField = value;
                    this.RaisePropertyChanged("QuantidadeDeParcelas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TaxaDeJuros {
            get {
                return this.TaxaDeJurosField;
            }
            set {
                if ((this.TaxaDeJurosField.Equals(value) != true)) {
                    this.TaxaDeJurosField = value;
                    this.RaisePropertyChanged("TaxaDeJuros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/WCFVideos.Contratos")]
    public enum Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aprovada = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejeitada = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmAnalise = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalhesDoErro", Namespace="http://schemas.datacontract.org/2004/07/WCFVideos.Contratos")]
    [System.SerializableAttribute()]
    public partial class DetalhesDoErro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoDeGestaoDeCredito.IGestorDeCredito", CallbackContract=typeof(WCFVideos.WebUI.ServicoDeGestaoDeCredito.IGestorDeCreditoCallback))]
    public interface IGestorDeCredito {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestorDeCredito/RecuperarQuantidadeDeRecursoDisponivel", ReplyAction="http://tempuri.org/IGestorDeCredito/RecuperarQuantidadeDeRecursoDisponivelRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFVideos.WebUI.ServicoDeGestaoDeCredito.DetalhesDoErro), Action="http://tempuri.org/IGestorDeCredito/RecuperarQuantidadeDeRecursoDisponivelDetalhe" +
            "sDoErroFault", Name="DetalhesDoErro", Namespace="http://schemas.datacontract.org/2004/07/WCFVideos.Contratos")]
        decimal RecuperarQuantidadeDeRecursoDisponivel();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IGestorDeCredito/RecuperarQuantidadeDeRecursoDisponivel", ReplyAction="http://tempuri.org/IGestorDeCredito/RecuperarQuantidadeDeRecursoDisponivelRespons" +
            "e")]
        System.IAsyncResult BeginRecuperarQuantidadeDeRecursoDisponivel(System.AsyncCallback callback, object asyncState);
        
        decimal EndRecuperarQuantidadeDeRecursoDisponivel(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestorDeCredito/AnalisarProposta")]
        void AnalisarProposta(WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta proposta);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://tempuri.org/IGestorDeCredito/AnalisarProposta")]
        System.IAsyncResult BeginAnalisarProposta(WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta proposta, System.AsyncCallback callback, object asyncState);
        
        void EndAnalisarProposta(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestorDeCredito/EfetivarProposta")]
        void EfetivarProposta(WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta proposta);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://tempuri.org/IGestorDeCredito/EfetivarProposta")]
        System.IAsyncResult BeginEfetivarProposta(WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta proposta, System.AsyncCallback callback, object asyncState);
        
        void EndEfetivarProposta(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestorDeCredito/RecuperarPropostas", ReplyAction="http://tempuri.org/IGestorDeCredito/RecuperarPropostasResponse")]
        WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta[] RecuperarPropostas(WCFVideos.WebUI.ServicoDeGestaoDeCredito.Status status);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IGestorDeCredito/RecuperarPropostas", ReplyAction="http://tempuri.org/IGestorDeCredito/RecuperarPropostasResponse")]
        System.IAsyncResult BeginRecuperarPropostas(WCFVideos.WebUI.ServicoDeGestaoDeCredito.Status status, System.AsyncCallback callback, object asyncState);
        
        WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta[] EndRecuperarPropostas(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestorDeCreditoCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestorDeCredito/PropostaAnalisada")]
        void PropostaAnalisada(WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta proposta);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://tempuri.org/IGestorDeCredito/PropostaAnalisada")]
        System.IAsyncResult BeginPropostaAnalisada(WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta proposta, System.AsyncCallback callback, object asyncState);
        
        void EndPropostaAnalisada(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestorDeCreditoChannel : WCFVideos.WebUI.ServicoDeGestaoDeCredito.IGestorDeCredito, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecuperarQuantidadeDeRecursoDisponivelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RecuperarQuantidadeDeRecursoDisponivelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public decimal Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecuperarPropostasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RecuperarPropostasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestorDeCreditoClient : System.ServiceModel.DuplexClientBase<WCFVideos.WebUI.ServicoDeGestaoDeCredito.IGestorDeCredito>, WCFVideos.WebUI.ServicoDeGestaoDeCredito.IGestorDeCredito {
        
        private BeginOperationDelegate onBeginRecuperarQuantidadeDeRecursoDisponivelDelegate;
        
        private EndOperationDelegate onEndRecuperarQuantidadeDeRecursoDisponivelDelegate;
        
        private System.Threading.SendOrPostCallback onRecuperarQuantidadeDeRecursoDisponivelCompletedDelegate;
        
        private BeginOperationDelegate onBeginAnalisarPropostaDelegate;
        
        private EndOperationDelegate onEndAnalisarPropostaDelegate;
        
        private System.Threading.SendOrPostCallback onAnalisarPropostaCompletedDelegate;
        
        private BeginOperationDelegate onBeginEfetivarPropostaDelegate;
        
        private EndOperationDelegate onEndEfetivarPropostaDelegate;
        
        private System.Threading.SendOrPostCallback onEfetivarPropostaCompletedDelegate;
        
        private BeginOperationDelegate onBeginRecuperarPropostasDelegate;
        
        private EndOperationDelegate onEndRecuperarPropostasDelegate;
        
        private System.Threading.SendOrPostCallback onRecuperarPropostasCompletedDelegate;
        
        public GestorDeCreditoClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GestorDeCreditoClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GestorDeCreditoClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GestorDeCreditoClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GestorDeCreditoClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public event System.EventHandler<RecuperarQuantidadeDeRecursoDisponivelCompletedEventArgs> RecuperarQuantidadeDeRecursoDisponivelCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AnalisarPropostaCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EfetivarPropostaCompleted;
        
        public event System.EventHandler<RecuperarPropostasCompletedEventArgs> RecuperarPropostasCompleted;
        
        public decimal RecuperarQuantidadeDeRecursoDisponivel() {
            return base.Channel.RecuperarQuantidadeDeRecursoDisponivel();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRecuperarQuantidadeDeRecursoDisponivel(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRecuperarQuantidadeDeRecursoDisponivel(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public decimal EndRecuperarQuantidadeDeRecursoDisponivel(System.IAsyncResult result) {
            return base.Channel.EndRecuperarQuantidadeDeRecursoDisponivel(result);
        }
        
        private System.IAsyncResult OnBeginRecuperarQuantidadeDeRecursoDisponivel(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginRecuperarQuantidadeDeRecursoDisponivel(callback, asyncState);
        }
        
        private object[] OnEndRecuperarQuantidadeDeRecursoDisponivel(System.IAsyncResult result) {
            decimal retVal = this.EndRecuperarQuantidadeDeRecursoDisponivel(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRecuperarQuantidadeDeRecursoDisponivelCompleted(object state) {
            if ((this.RecuperarQuantidadeDeRecursoDisponivelCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RecuperarQuantidadeDeRecursoDisponivelCompleted(this, new RecuperarQuantidadeDeRecursoDisponivelCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RecuperarQuantidadeDeRecursoDisponivelAsync() {
            this.RecuperarQuantidadeDeRecursoDisponivelAsync(null);
        }
        
        public void RecuperarQuantidadeDeRecursoDisponivelAsync(object userState) {
            if ((this.onBeginRecuperarQuantidadeDeRecursoDisponivelDelegate == null)) {
                this.onBeginRecuperarQuantidadeDeRecursoDisponivelDelegate = new BeginOperationDelegate(this.OnBeginRecuperarQuantidadeDeRecursoDisponivel);
            }
            if ((this.onEndRecuperarQuantidadeDeRecursoDisponivelDelegate == null)) {
                this.onEndRecuperarQuantidadeDeRecursoDisponivelDelegate = new EndOperationDelegate(this.OnEndRecuperarQuantidadeDeRecursoDisponivel);
            }
            if ((this.onRecuperarQuantidadeDeRecursoDisponivelCompletedDelegate == null)) {
                this.onRecuperarQuantidadeDeRecursoDisponivelCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRecuperarQuantidadeDeRecursoDisponivelCompleted);
            }
            base.InvokeAsync(this.onBeginRecuperarQuantidadeDeRecursoDisponivelDelegate, null, this.onEndRecuperarQuantidadeDeRecursoDisponivelDelegate, this.onRecuperarQuantidadeDeRecursoDisponivelCompletedDelegate, userState);
        }
        
        public void AnalisarProposta(WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta proposta) {
            base.Channel.AnalisarProposta(proposta);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAnalisarProposta(WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta proposta, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAnalisarProposta(proposta, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndAnalisarProposta(System.IAsyncResult result) {
            base.Channel.EndAnalisarProposta(result);
        }
        
        private System.IAsyncResult OnBeginAnalisarProposta(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta proposta = ((WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta)(inValues[0]));
            return this.BeginAnalisarProposta(proposta, callback, asyncState);
        }
        
        private object[] OnEndAnalisarProposta(System.IAsyncResult result) {
            this.EndAnalisarProposta(result);
            return null;
        }
        
        private void OnAnalisarPropostaCompleted(object state) {
            if ((this.AnalisarPropostaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AnalisarPropostaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AnalisarPropostaAsync(WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta proposta) {
            this.AnalisarPropostaAsync(proposta, null);
        }
        
        public void AnalisarPropostaAsync(WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta proposta, object userState) {
            if ((this.onBeginAnalisarPropostaDelegate == null)) {
                this.onBeginAnalisarPropostaDelegate = new BeginOperationDelegate(this.OnBeginAnalisarProposta);
            }
            if ((this.onEndAnalisarPropostaDelegate == null)) {
                this.onEndAnalisarPropostaDelegate = new EndOperationDelegate(this.OnEndAnalisarProposta);
            }
            if ((this.onAnalisarPropostaCompletedDelegate == null)) {
                this.onAnalisarPropostaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAnalisarPropostaCompleted);
            }
            base.InvokeAsync(this.onBeginAnalisarPropostaDelegate, new object[] {
                        proposta}, this.onEndAnalisarPropostaDelegate, this.onAnalisarPropostaCompletedDelegate, userState);
        }
        
        public void EfetivarProposta(WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta proposta) {
            base.Channel.EfetivarProposta(proposta);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginEfetivarProposta(WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta proposta, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEfetivarProposta(proposta, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndEfetivarProposta(System.IAsyncResult result) {
            base.Channel.EndEfetivarProposta(result);
        }
        
        private System.IAsyncResult OnBeginEfetivarProposta(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta proposta = ((WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta)(inValues[0]));
            return this.BeginEfetivarProposta(proposta, callback, asyncState);
        }
        
        private object[] OnEndEfetivarProposta(System.IAsyncResult result) {
            this.EndEfetivarProposta(result);
            return null;
        }
        
        private void OnEfetivarPropostaCompleted(object state) {
            if ((this.EfetivarPropostaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EfetivarPropostaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EfetivarPropostaAsync(WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta proposta) {
            this.EfetivarPropostaAsync(proposta, null);
        }
        
        public void EfetivarPropostaAsync(WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta proposta, object userState) {
            if ((this.onBeginEfetivarPropostaDelegate == null)) {
                this.onBeginEfetivarPropostaDelegate = new BeginOperationDelegate(this.OnBeginEfetivarProposta);
            }
            if ((this.onEndEfetivarPropostaDelegate == null)) {
                this.onEndEfetivarPropostaDelegate = new EndOperationDelegate(this.OnEndEfetivarProposta);
            }
            if ((this.onEfetivarPropostaCompletedDelegate == null)) {
                this.onEfetivarPropostaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEfetivarPropostaCompleted);
            }
            base.InvokeAsync(this.onBeginEfetivarPropostaDelegate, new object[] {
                        proposta}, this.onEndEfetivarPropostaDelegate, this.onEfetivarPropostaCompletedDelegate, userState);
        }
        
        public WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta[] RecuperarPropostas(WCFVideos.WebUI.ServicoDeGestaoDeCredito.Status status) {
            return base.Channel.RecuperarPropostas(status);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRecuperarPropostas(WCFVideos.WebUI.ServicoDeGestaoDeCredito.Status status, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRecuperarPropostas(status, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta[] EndRecuperarPropostas(System.IAsyncResult result) {
            return base.Channel.EndRecuperarPropostas(result);
        }
        
        private System.IAsyncResult OnBeginRecuperarPropostas(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WCFVideos.WebUI.ServicoDeGestaoDeCredito.Status status = ((WCFVideos.WebUI.ServicoDeGestaoDeCredito.Status)(inValues[0]));
            return this.BeginRecuperarPropostas(status, callback, asyncState);
        }
        
        private object[] OnEndRecuperarPropostas(System.IAsyncResult result) {
            WCFVideos.WebUI.ServicoDeGestaoDeCredito.Proposta[] retVal = this.EndRecuperarPropostas(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRecuperarPropostasCompleted(object state) {
            if ((this.RecuperarPropostasCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RecuperarPropostasCompleted(this, new RecuperarPropostasCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RecuperarPropostasAsync(WCFVideos.WebUI.ServicoDeGestaoDeCredito.Status status) {
            this.RecuperarPropostasAsync(status, null);
        }
        
        public void RecuperarPropostasAsync(WCFVideos.WebUI.ServicoDeGestaoDeCredito.Status status, object userState) {
            if ((this.onBeginRecuperarPropostasDelegate == null)) {
                this.onBeginRecuperarPropostasDelegate = new BeginOperationDelegate(this.OnBeginRecuperarPropostas);
            }
            if ((this.onEndRecuperarPropostasDelegate == null)) {
                this.onEndRecuperarPropostasDelegate = new EndOperationDelegate(this.OnEndRecuperarPropostas);
            }
            if ((this.onRecuperarPropostasCompletedDelegate == null)) {
                this.onRecuperarPropostasCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRecuperarPropostasCompleted);
            }
            base.InvokeAsync(this.onBeginRecuperarPropostasDelegate, new object[] {
                        status}, this.onEndRecuperarPropostasDelegate, this.onRecuperarPropostasCompletedDelegate, userState);
        }
    }
}
